
GET http://localhost:3003/user/all

###


PUT http://localhost:3003/user
Content-Type: application/json

{
	"id": 3,
    "name": "Alan",
	"nickname": "Al",
	"email": "al@dev.com"
}

### 

GET http://localhost:3003/user/3

###

POST http://localhost:3003/user/edit/1
Content-Type: application/json

{
    "name": "Marivone",
	"nickname": "Marz",
}










