# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Timothy Hunter", 
   "nickname": "sorcerer", 
   "email": "boy@booksofmagic.com" ,
   "password": "1990101"
}

###
# @name login

POST http://localhost:3003/user/login
Content-Type: application/json

{
 
   "email": "littlesister@writer.com" ,
   "password": "342131"
}

###

GET http://localhost:3003/user/da5ed2d6-9172-4f8b-a1df-71a1c0650f3c


###

###

GET http://localhost:3003/user/king@writer.com

###

